// Команда gencodes генерирует Go-константы кодов событий ввода Linux
// из заголовка ядра linux/input-event-codes.h (T1.1).
//
// Использование: go run ./tools/gencodes [-in /usr/include/linux/input-event-codes.h] [-out internal/lib/evdev/codes_gen.go]
//
// Сгенерированный файл хранится в репозитории, поэтому для обычной сборки заголовки
// ядра не нужны; генератор запускают только при обновлении списка кодов.
// Генерировать таблицу, а не набирать её вручную, важно: ошибка в одном коде
// означает «не та клавиша» у пользователя.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// prefixes — группы кодов, которые попадают в сгенерированный файл, в порядке вывода.
var prefixes = []string{"EV", "SYN", "KEY", "BTN", "REL", "ABS", "MSC", "SW", "LED", "SND", "REP", "FF", "INPUT_PROP"}

// defineRe разбирает строку вида "#define NAME value".
var defineRe = regexp.MustCompile(`^#define\s+([A-Z][A-Z0-9_]*)\s+(.+?)\s*(?:/\*.*)?$`)

// exprRe разбирает простые выражения вида "(NAME+1)", встречающиеся в *_CNT.
var exprRe = regexp.MustCompile(`^\(\s*([A-Z][A-Z0-9_]*)\s*\+\s*(\d+)\s*\)$`)

// define — одна разобранная константа.
type define struct {
	name  string
	value int64
	// alias — константа определена через имя другой константы (например, BTN_A = BTN_SOUTH).
	alias bool
}

// main читает заголовок, разбирает константы и записывает Go-файл.
func main() {
	// Разбираем аргументы командной строки.
	in := flag.String("in", "/usr/include/linux/input-event-codes.h", "path to input-event-codes.h")
	out := flag.String("out", "internal/lib/evdev/codes_gen.go", "output Go file")
	flag.Parse()

	// Читаем и разбираем заголовок.
	f, err := os.Open(*in)
	if err != nil {
		fail(err)
	}
	defs, err := parse(f)
	_ = f.Close()
	if err != nil {
		fail(err)
	}

	// Генерируем и записываем Go-код.
	src, err := render(defs)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("gencodes: %d constants written to %s\n", len(defs), *out)
}

// fail печатает ошибку и завершает процесс с кодом 1.
func fail(err error) {
	fmt.Fprintln(os.Stderr, "gencodes:", err)
	os.Exit(1)
}

// parse извлекает из заголовка все константы нужных групп в порядке появления.
// Значение может быть числом, именем ранее определённой константы или выражением (NAME+N).
func parse(r io.Reader) ([]define, error) {
	values := map[string]int64{}
	var defs []define
	sc := bufio.NewScanner(r)
	for sc.Scan() {
		// Отбираем только #define из нужных групп.
		m := defineRe.FindStringSubmatch(strings.TrimSpace(sc.Text()))
		if m == nil || !wanted(m[1]) {
			continue
		}
		name, raw := m[1], strings.TrimSpace(m[2])

		// Вычисляем значение: число, ссылка на другую константу или выражение (NAME+N).
		var d define
		switch {
		case isNumber(raw):
			v, err := strconv.ParseInt(raw, 0, 64)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", name, err)
			}
			d = define{name: name, value: v}
		case isKnown(values, raw):
			d = define{name: name, value: values[raw], alias: true}
		default:
			em := exprRe.FindStringSubmatch(raw)
			if em == nil || !isKnown(values, em[1]) {
				return nil, fmt.Errorf("%s: unsupported value %q", name, raw)
			}
			n, _ := strconv.ParseInt(em[2], 10, 64)
			d = define{name: name, value: values[em[1]] + n, alias: true}
		}
		values[name] = d.value
		defs = append(defs, d)
	}
	return defs, sc.Err()
}

// wanted сообщает, относится ли константа к одной из генерируемых групп.
func wanted(name string) bool {
	for _, p := range prefixes {
		if strings.HasPrefix(name, p+"_") {
			return true
		}
	}
	return false
}

// isNumber сообщает, является ли строка десятичным или шестнадцатеричным литералом.
func isNumber(s string) bool {
	_, err := strconv.ParseInt(s, 0, 64)
	return err == nil
}

// isKnown сообщает, была ли константа name уже определена.
func isKnown(values map[string]int64, name string) bool {
	_, ok := values[name]
	return ok
}

// render формирует Go-файл с константами и таблицами «код → имя» по группам.
func render(defs []define) ([]byte, error) {
	var b bytes.Buffer

	// Шапка файла.
	b.WriteString("// Code generated by tools/gencodes from linux/input-event-codes.h. DO NOT EDIT.\n\n")
	b.WriteString("package evdev\n\n")

	// Все константы одним блоком. Имена переводятся в Go-стиль: KEY_LEFTCTRL → KeyLeftctrl.
	b.WriteString("// Коды событий ввода Linux (см. linux/input-event-codes.h).\nconst (\n")
	for _, d := range defs {
		fmt.Fprintf(&b, "\t%s = 0x%x // %s\n", goName(d.name), d.value, d.name)
	}
	b.WriteString(")\n\n")

	// Таблицы «код → каноническое имя ядра» по группам; для кода берётся первое
	// числовое (не алиасное) определение, например BTN_SOUTH, а не BTN_A.
	groups := map[string]map[int64]string{}
	for _, d := range defs {
		g := groupOf(d.name)
		if g == "" || d.alias || isLimit(d.name) {
			continue
		}
		if groups[g] == nil {
			groups[g] = map[int64]string{}
		}
		if _, exists := groups[g][d.value]; !exists {
			groups[g][d.value] = d.name
		}
	}
	names := make([]string, 0, len(groups))
	for g := range groups {
		names = append(names, g)
	}
	sort.Strings(names)
	b.WriteString("// codeNames — канонические имена кодов ядра по группам: группа → код → имя.\n")
	b.WriteString("var codeNames = map[string]map[uint16]string{\n")
	for _, g := range names {
		fmt.Fprintf(&b, "\t%q: {\n", g)
		codes := make([]int64, 0, len(groups[g]))
		for c := range groups[g] {
			codes = append(codes, c)
		}
		sort.Slice(codes, func(i, j int) bool { return codes[i] < codes[j] })
		for _, c := range codes {
			fmt.Fprintf(&b, "\t\t0x%x: %q,\n", c, groups[g][c])
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	// Форматируем результат, как gofmt.
	return format.Source(b.Bytes())
}

// groupOf возвращает группу кода для таблицы имён: KEY и BTN объединены в "KEY"
// (оба — события EV_KEY), остальные группы — по префиксу.
func groupOf(name string) string {
	switch {
	case strings.HasPrefix(name, "KEY_"), strings.HasPrefix(name, "BTN_"):
		return "KEY"
	case strings.HasPrefix(name, "INPUT_PROP_"):
		return "INPUT_PROP"
	}
	for _, p := range prefixes {
		if strings.HasPrefix(name, p+"_") {
			return p
		}
	}
	return ""
}

// isLimit сообщает, является ли константа служебной границей диапазона (_MAX, _CNT, _MIN…),
// а не кодом конкретной клавиши/оси.
func isLimit(name string) bool {
	for _, s := range []string{"_MAX", "_CNT", "_MIN_INTERESTING"} {
		if strings.HasSuffix(name, s) {
			return true
		}
	}
	return name == "BTN_MISC" || name == "BTN_MOUSE" || name == "BTN_JOYSTICK" ||
		name == "BTN_GAMEPAD" || name == "BTN_DIGI" || name == "BTN_WHEEL" || name == "BTN_TRIGGER_HAPPY"
}

// goName переводит имя ядра в имя Go-константы: KEY_LEFTCTRL → KeyLeftctrl, INPUT_PROP_DIRECT → InputPropDirect.
func goName(name string) string {
	parts := strings.Split(strings.ToLower(name), "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
