// Code generated by tools/gencodes from linux/input-event-codes.h. DO NOT EDIT.

package evdev

// Коды событий ввода Linux (см. linux/input-event-codes.h).
const (
	InputPropPointer           = 0x0   // INPUT_PROP_POINTER
	InputPropDirect            = 0x1   // INPUT_PROP_DIRECT
	InputPropButtonpad         = 0x2   // INPUT_PROP_BUTTONPAD
	InputPropSemiMt            = 0x3   // INPUT_PROP_SEMI_MT
	InputPropTopbuttonpad      = 0x4   // INPUT_PROP_TOPBUTTONPAD
	InputPropPointingStick     = 0x5   // INPUT_PROP_POINTING_STICK
	InputPropAccelerometer     = 0x6   // INPUT_PROP_ACCELEROMETER
	InputPropMax               = 0x1f  // INPUT_PROP_MAX
	InputPropCnt               = 0x20  // INPUT_PROP_CNT
	EvSyn                      = 0x0   // EV_SYN
	EvKey                      = 0x1   // EV_KEY
	EvRel                      = 0x2   // EV_REL
	EvAbs                      = 0x3   // EV_ABS
	EvMsc                      = 0x4   // EV_MSC
	EvSw                       = 0x5   // EV_SW
	EvLed                      = 0x11  // EV_LED
	EvSnd                      = 0x12  // EV_SND
	EvRep                      = 0x14  // EV_REP
	EvFf                       = 0x15  // EV_FF
	EvPwr                      = 0x16  // EV_PWR
	EvFfStatus                 = 0x17  // EV_FF_STATUS
	EvMax                      = 0x1f  // EV_MAX
	EvCnt                      = 0x20  // EV_CNT
	SynReport                  = 0x0   // SYN_REPORT
	SynConfig                  = 0x1   // SYN_CONFIG
	SynMtReport                = 0x2   // SYN_MT_REPORT
	SynDropped                 = 0x3   // SYN_DROPPED
	SynMax                     = 0xf   // SYN_MAX
	SynCnt                     = 0x10  // SYN_CNT
	KeyReserved                = 0x0   // KEY_RESERVED
	KeyEsc                     = 0x1   // KEY_ESC
	Key1                       = 0x2   // KEY_1
	Key2                       = 0x3   // KEY_2
	Key3                       = 0x4   // KEY_3
	Key4                       = 0x5   // KEY_4
	Key5                       = 0x6   // KEY_5
	Key6                       = 0x7   // KEY_6
	Key7                       = 0x8   // KEY_7
	Key8                       = 0x9   // KEY_8
	Key9                       = 0xa   // KEY_9
	Key0                       = 0xb   // KEY_0
	KeyMinus                   = 0xc   // KEY_MINUS
	KeyEqual                   = 0xd   // KEY_EQUAL
	KeyBackspace               = 0xe   // KEY_BACKSPACE
	KeyTab                     = 0xf   // KEY_TAB
	KeyQ                       = 0x10  // KEY_Q
	KeyW                       = 0x11  // KEY_W
	KeyE                       = 0x12  // KEY_E
	KeyR                       = 0x13  // KEY_R
	KeyT                       = 0x14  // KEY_T
	KeyY                       = 0x15  // KEY_Y
	KeyU                       = 0x16  // KEY_U
	KeyI                       = 0x17  // KEY_I
	KeyO                       = 0x18  // KEY_O
	KeyP                       = 0x19  // KEY_P
	KeyLeftbrace               = 0x1a  // KEY_LEFTBRACE
	KeyRightbrace              = 0x1b  // KEY_RIGHTBRACE
	KeyEnter                   = 0x1c  // KEY_ENTER
	KeyLeftctrl                = 0x1d  // KEY_LEFTCTRL
	KeyA                       = 0x1e  // KEY_A
	KeyS                       = 0x1f  // KEY_S
	KeyD                       = 0x20  // KEY_D
	KeyF                       = 0x21  // KEY_F
	KeyG                       = 0x22  // KEY_G
	KeyH                       = 0x23  // KEY_H
	KeyJ                       = 0x24  // KEY_J
	KeyK                       = 0x25  // KEY_K
	KeyL                       = 0x26  // KEY_L
	KeySemicolon               = 0x27  // KEY_SEMICOLON
	KeyApostrophe              = 0x28  // KEY_APOSTROPHE
	KeyGrave                   = 0x29  // KEY_GRAVE
	KeyLeftshift               = 0x2a  // KEY_LEFTSHIFT
	KeyBackslash               = 0x2b  // KEY_BACKSLASH
	KeyZ                       = 0x2c  // KEY_Z
	KeyX                       = 0x2d  // KEY_X
	KeyC                       = 0x2e  // KEY_C
	KeyV                       = 0x2f  // KEY_V
	KeyB                       = 0x30  // KEY_B
	KeyN                       = 0x31  // KEY_N
	KeyM                       = 0x32  // KEY_M
	KeyComma                   = 0x33  // KEY_COMMA
	KeyDot                     = 0x34  // KEY_DOT
	KeySlash                   = 0x35  // KEY_SLASH
	KeyRightshift              = 0x36  // KEY_RIGHTSHIFT
	KeyKpasterisk              = 0x37  // KEY_KPASTERISK
	KeyLeftalt                 = 0x38  // KEY_LEFTALT
	KeySpace                   = 0x39  // KEY_SPACE
	KeyCapslock                = 0x3a  // KEY_CAPSLOCK
	KeyF1                      = 0x3b  // KEY_F1
	KeyF2                      = 0x3c  // KEY_F2
	KeyF3                      = 0x3d  // KEY_F3
	KeyF4                      = 0x3e  // KEY_F4
	KeyF5                      = 0x3f  // KEY_F5
	KeyF6                      = 0x40  // KEY_F6
	KeyF7                      = 0x41  // KEY_F7
	KeyF8                      = 0x42  // KEY_F8
	KeyF9                      = 0x43  // KEY_F9
	KeyF10                     = 0x44  // KEY_F10
	KeyNumlock                 = 0x45  // KEY_NUMLOCK
	KeyScrolllock              = 0x46  // KEY_SCROLLLOCK
	KeyKp7                     = 0x47  // KEY_KP7
	KeyKp8                     = 0x48  // KEY_KP8
	KeyKp9                     = 0x49  // KEY_KP9
	KeyKpminus                 = 0x4a  // KEY_KPMINUS
	KeyKp4                     = 0x4b  // KEY_KP4
	KeyKp5                     = 0x4c  // KEY_KP5
	KeyKp6                     = 0x4d  // KEY_KP6
	KeyKpplus                  = 0x4e  // KEY_KPPLUS
	KeyKp1                     = 0x4f  // KEY_KP1
	KeyKp2                     = 0x50  // KEY_KP2
	KeyKp3                     = 0x51  // KEY_KP3
	KeyKp0                     = 0x52  // KEY_KP0
	KeyKpdot                   = 0x53  // KEY_KPDOT
	KeyZenkakuhankaku          = 0x55  // KEY_ZENKAKUHANKAKU
	Key102nd                   = 0x56  // KEY_102ND
	KeyF11                     = 0x57  // KEY_F11
	KeyF12                     = 0x58  // KEY_F12
	KeyRo                      = 0x59  // KEY_RO
	KeyKatakana                = 0x5a  // KEY_KATAKANA
	KeyHiragana                = 0x5b  // KEY_HIRAGANA
	KeyHenkan                  = 0x5c  // KEY_HENKAN
	KeyKatakanahiragana        = 0x5d  // KEY_KATAKANAHIRAGANA
	KeyMuhenkan                = 0x5e  // KEY_MUHENKAN
	KeyKpjpcomma               = 0x5f  // KEY_KPJPCOMMA
	KeyKpenter                 = 0x60  // KEY_KPENTER
	KeyRightctrl               = 0x61  // KEY_RIGHTCTRL
	KeyKpslash                 = 0x62  // KEY_KPSLASH
	KeySysrq                   = 0x63  // KEY_SYSRQ
	KeyRightalt                = 0x64  // KEY_RIGHTALT
	KeyLinefeed                = 0x65  // KEY_LINEFEED
	KeyHome                    = 0x66  // KEY_HOME
	KeyUp                      = 0x67  // KEY_UP
	KeyPageup                  = 0x68  // KEY_PAGEUP
	KeyLeft                    = 0x69  // KEY_LEFT
	KeyRight                   = 0x6a  // KEY_RIGHT
	KeyEnd                     = 0x6b  // KEY_END
	KeyDown                    = 0x6c  // KEY_DOWN
	KeyPagedown                = 0x6d  // KEY_PAGEDOWN
	KeyInsert                  = 0x6e  // KEY_INSERT
	KeyDelete                  = 0x6f  // KEY_DELETE
	KeyMacro                   = 0x70  // KEY_MACRO
	KeyMute                    = 0x71  // KEY_MUTE
	KeyVolumedown              = 0x72  // KEY_VOLUMEDOWN
	KeyVolumeup                = 0x73  // KEY_VOLUMEUP
	KeyPower                   = 0x74  // KEY_POWER
	KeyKpequal                 = 0x75  // KEY_KPEQUAL
	KeyKpplusminus             = 0x76  // KEY_KPPLUSMINUS
	KeyPause                   = 0x77  // KEY_PAUSE
	KeyScale                   = 0x78  // KEY_SCALE
	KeyKpcomma                 = 0x79  // KEY_KPCOMMA
	KeyHangeul                 = 0x7a  // KEY_HANGEUL
	KeyHanguel                 = 0x7a  // KEY_HANGUEL
	KeyHanja                   = 0x7b  // KEY_HANJA
	KeyYen                     = 0x7c  // KEY_YEN
	KeyLeftmeta                = 0x7d  // KEY_LEFTMETA
	KeyRightmeta               = 0x7e  // KEY_RIGHTMETA
	KeyCompose                 = 0x7f  // KEY_COMPOSE
	KeyStop                    = 0x80  // KEY_STOP
	KeyAgain                   = 0x81  // KEY_AGAIN
	KeyProps                   = 0x82  // KEY_PROPS
	KeyUndo                    = 0x83  // KEY_UNDO
	KeyFront                   = 0x84  // KEY_FRONT
	KeyCopy                    = 0x85  // KEY_COPY
	KeyOpen                    = 0x86  // KEY_OPEN
	KeyPaste                   = 0x87  // KEY_PASTE
	KeyFind                    = 0x88  // KEY_FIND
	KeyCut                     = 0x89  // KEY_CUT
	KeyHelp                    = 0x8a  // KEY_HELP
	KeyMenu                    = 0x8b  // KEY_MENU
	KeyCalc                    = 0x8c  // KEY_CALC
	KeySetup                   = 0x8d  // KEY_SETUP
	KeySleep                   = 0x8e  // KEY_SLEEP
	KeyWakeup                  = 0x8f  // KEY_WAKEUP
	KeyFile                    = 0x90  // KEY_FILE
	KeySendfile                = 0x91  // KEY_SENDFILE
	KeyDeletefile              = 0x92  // KEY_DELETEFILE
	KeyXfer                    = 0x93  // KEY_XFER
	KeyProg1                   = 0x94  // KEY_PROG1
	KeyProg2                   = 0x95  // KEY_PROG2
	KeyWww                     = 0x96  // KEY_WWW
	KeyMsdos                   = 0x97  // KEY_MSDOS
	KeyCoffee                  = 0x98  // KEY_COFFEE
	KeyScreenlock              = 0x98  // KEY_SCREENLOCK
	KeyRotateDisplay           = 0x99  // KEY_ROTATE_DISPLAY
	KeyDirection               = 0x99  // KEY_DIRECTION
	KeyCyclewindows            = 0x9a  // KEY_CYCLEWINDOWS
	KeyMail                    = 0x9b  // KEY_MAIL
	KeyBookmarks               = 0x9c  // KEY_BOOKMARKS
	KeyComputer                = 0x9d  // KEY_COMPUTER
	KeyBack                    = 0x9e  // KEY_BACK
	KeyForward                 = 0x9f  // KEY_FORWARD
	KeyClosecd                 = 0xa0  // KEY_CLOSECD
	KeyEjectcd                 = 0xa1  // KEY_EJECTCD
	KeyEjectclosecd            = 0xa2  // KEY_EJECTCLOSECD
	KeyNextsong                = 0xa3  // KEY_NEXTSONG
	KeyPlaypause               = 0xa4  // KEY_PLAYPAUSE
	KeyPrevioussong            = 0xa5  // KEY_PREVIOUSSONG
	KeyStopcd                  = 0xa6  // KEY_STOPCD
	KeyRecord                  = 0xa7  // KEY_RECORD
	KeyRewind                  = 0xa8  // KEY_REWIND
	KeyPhone                   = 0xa9  // KEY_PHONE
	KeyIso                     = 0xaa  // KEY_ISO
	KeyConfig                  = 0xab  // KEY_CONFIG
	KeyHomepage                = 0xac  // KEY_HOMEPAGE
	KeyRefresh                 = 0xad  // KEY_REFRESH
	KeyExit                    = 0xae  // KEY_EXIT
	KeyMove                    = 0xaf  // KEY_MOVE
	KeyEdit                    = 0xb0  // KEY_EDIT
	KeyScrollup                = 0xb1  // KEY_SCROLLUP
	KeyScrolldown              = 0xb2  // KEY_SCROLLDOWN
	KeyKpleftparen             = 0xb3  // KEY_KPLEFTPAREN
	KeyKprightparen            = 0xb4  // KEY_KPRIGHTPAREN
	KeyNew                     = 0xb5  // KEY_NEW
	KeyRedo                    = 0xb6  // KEY_REDO
	KeyF13                     = 0xb7  // KEY_F13
	KeyF14                     = 0xb8  // KEY_F14
	KeyF15                     = 0xb9  // KEY_F15
	KeyF16                     = 0xba  // KEY_F16
	KeyF17                     = 0xbb  // KEY_F17
	KeyF18                     = 0xbc  // KEY_F18
	KeyF19                     = 0xbd  // KEY_F19
	KeyF20                     = 0xbe  // KEY_F20
	KeyF21                     = 0xbf  // KEY_F21
	KeyF22                     = 0xc0  // KEY_F22
	KeyF23                     = 0xc1  // KEY_F23
	KeyF24                     = 0xc2  // KEY_F24
	KeyPlaycd                  = 0xc8  // KEY_PLAYCD
	KeyPausecd                 = 0xc9  // KEY_PAUSECD
	KeyProg3                   = 0xca  // KEY_PROG3
	KeyProg4                   = 0xcb  // KEY_PROG4
	KeyAllApplications         = 0xcc  // KEY_ALL_APPLICATIONS
	KeyDashboard               = 0xcc  // KEY_DASHBOARD
	KeySuspend                 = 0xcd  // KEY_SUSPEND
	KeyClose                   = 0xce  // KEY_CLOSE
	KeyPlay                    = 0xcf  // KEY_PLAY
	KeyFastforward             = 0xd0  // KEY_FASTFORWARD
	KeyBassboost               = 0xd1  // KEY_BASSBOOST
	KeyPrint                   = 0xd2  // KEY_PRINT
	KeyHp                      = 0xd3  // KEY_HP
	KeyCamera                  = 0xd4  // KEY_CAMERA
	KeySound                   = 0xd5  // KEY_SOUND
	KeyQuestion                = 0xd6  // KEY_QUESTION
	KeyEmail                   = 0xd7  // KEY_EMAIL
	KeyChat                    = 0xd8  // KEY_CHAT
	KeySearch                  = 0xd9  // KEY_SEARCH
	KeyConnect                 = 0xda  // KEY_CONNECT
	KeyFinance                 = 0xdb  // KEY_FINANCE
	KeySport                   = 0xdc  // KEY_SPORT
	KeyShop                    = 0xdd  // KEY_SHOP
	KeyAlterase                = 0xde  // KEY_ALTERASE
	KeyCancel                  = 0xdf  // KEY_CANCEL
	KeyBrightnessdown          = 0xe0  // KEY_BRIGHTNESSDOWN
	KeyBrightnessup            = 0xe1  // KEY_BRIGHTNESSUP
	KeyMedia                   = 0xe2  // KEY_MEDIA
	KeySwitchvideomode         = 0xe3  // KEY_SWITCHVIDEOMODE
	KeyKbdillumtoggle          = 0xe4  // KEY_KBDILLUMTOGGLE
	KeyKbdillumdown            = 0xe5  // KEY_KBDILLUMDOWN
	KeyKbdillumup              = 0xe6  // KEY_KBDILLUMUP
	KeySend                    = 0xe7  // KEY_SEND
	KeyReply                   = 0xe8  // KEY_REPLY
	KeyForwardmail             = 0xe9  // KEY_FORWARDMAIL
	KeySave                    = 0xea  // KEY_SAVE
	KeyDocuments               = 0xeb  // KEY_DOCUMENTS
	KeyBattery                 = 0xec  // KEY_BATTERY
	KeyBluetooth               = 0xed  // KEY_BLUETOOTH
	KeyWlan                    = 0xee  // KEY_WLAN
	KeyUwb                     = 0xef  // KEY_UWB
	KeyUnknown                 = 0xf0  // KEY_UNKNOWN
	KeyVideoNext               = 0xf1  // KEY_VIDEO_NEXT
	KeyVideoPrev               = 0xf2  // KEY_VIDEO_PREV
	KeyBrightnessCycle         = 0xf3  // KEY_BRIGHTNESS_CYCLE
	KeyBrightnessAuto          = 0xf4  // KEY_BRIGHTNESS_AUTO
	KeyBrightnessZero          = 0xf4  // KEY_BRIGHTNESS_ZERO
	KeyDisplayOff              = 0xf5  // KEY_DISPLAY_OFF
	KeyWwan                    = 0xf6  // KEY_WWAN
	KeyWimax                   = 0xf6  // KEY_WIMAX
	KeyRfkill                  = 0xf7  // KEY_RFKILL
	KeyMicmute                 = 0xf8  // KEY_MICMUTE
	BtnMisc                    = 0x100 // BTN_MISC
	Btn0                       = 0x100 // BTN_0
	Btn1                       = 0x101 // BTN_1
	Btn2                       = 0x102 // BTN_2
	Btn3                       = 0x103 // BTN_3
	Btn4                       = 0x104 // BTN_4
	Btn5                       = 0x105 // BTN_5
	Btn6                       = 0x106 // BTN_6
	Btn7                       = 0x107 // BTN_7
	Btn8                       = 0x108 // BTN_8
	Btn9                       = 0x109 // BTN_9
	BtnMouse                   = 0x110 // BTN_MOUSE
	BtnLeft                    = 0x110 // BTN_LEFT
	BtnRight                   = 0x111 // BTN_RIGHT
	BtnMiddle                  = 0x112 // BTN_MIDDLE
	BtnSide                    = 0x113 // BTN_SIDE
	BtnExtra                   = 0x114 // BTN_EXTRA
	BtnForward                 = 0x115 // BTN_FORWARD
	BtnBack                    = 0x116 // BTN_BACK
	BtnTask                    = 0x117 // BTN_TASK
	BtnJoystick                = 0x120 // BTN_JOYSTICK
	BtnTrigger                 = 0x120 // BTN_TRIGGER
	BtnThumb                   = 0x121 // BTN_THUMB
	BtnThumb2                  = 0x122 // BTN_THUMB2
	BtnTop                     = 0x123 // BTN_TOP
	BtnTop2                    = 0x124 // BTN_TOP2
	BtnPinkie                  = 0x125 // BTN_PINKIE
	BtnBase                    = 0x126 // BTN_BASE
	BtnBase2                   = 0x127 // BTN_BASE2
	BtnBase3                   = 0x128 // BTN_BASE3
	BtnBase4                   = 0x129 // BTN_BASE4
	BtnBase5                   = 0x12a // BTN_BASE5
	BtnBase6                   = 0x12b // BTN_BASE6
	BtnDead                    = 0x12f // BTN_DEAD
	BtnGamepad                 = 0x130 // BTN_GAMEPAD
	BtnSouth                   = 0x130 // BTN_SOUTH
	BtnA                       = 0x130 // BTN_A
	BtnEast                    = 0x131 // BTN_EAST
	BtnB                       = 0x131 // BTN_B
	BtnC                       = 0x132 // BTN_C
	BtnNorth                   = 0x133 // BTN_NORTH
	BtnX                       = 0x133 // BTN_X
	BtnWest                    = 0x134 // BTN_WEST
	BtnY                       = 0x134 // BTN_Y
	BtnZ                       = 0x135 // BTN_Z
	BtnTl                      = 0x136 // BTN_TL
	BtnTr                      = 0x137 // BTN_TR
	BtnTl2                     = 0x138 // BTN_TL2
	BtnTr2                     = 0x139 // BTN_TR2
	BtnSelect                  = 0x13a // BTN_SELECT
	BtnStart                   = 0x13b // BTN_START
	BtnMode                    = 0x13c // BTN_MODE
	BtnThumbl                  = 0x13d // BTN_THUMBL
	BtnThumbr                  = 0x13e // BTN_THUMBR
	BtnDigi                    = 0x140 // BTN_DIGI
	BtnToolPen                 = 0x140 // BTN_TOOL_PEN
	BtnToolRubber              = 0x141 // BTN_TOOL_RUBBER
	BtnToolBrush               = 0x142 // BTN_TOOL_BRUSH
	BtnToolPencil              = 0x143 // BTN_TOOL_PENCIL
	BtnToolAirbrush            = 0x144 // BTN_TOOL_AIRBRUSH
	BtnToolFinger              = 0x145 // BTN_TOOL_FINGER
	BtnToolMouse               = 0x146 // BTN_TOOL_MOUSE
	BtnToolLens                = 0x147 // BTN_TOOL_LENS
	BtnToolQuinttap            = 0x148 // BTN_TOOL_QUINTTAP
	BtnStylus3                 = 0x149 // BTN_STYLUS3
	BtnTouch                   = 0x14a // BTN_TOUCH
	BtnStylus                  = 0x14b // BTN_STYLUS
	BtnStylus2                 = 0x14c // BTN_STYLUS2
	BtnToolDoubletap           = 0x14d // BTN_TOOL_DOUBLETAP
	BtnToolTripletap           = 0x14e // BTN_TOOL_TRIPLETAP
	BtnToolQuadtap             = 0x14f // BTN_TOOL_QUADTAP
	BtnWheel                   = 0x150 // BTN_WHEEL
	BtnGearDown                = 0x150 // BTN_GEAR_DOWN
	BtnGearUp                  = 0x151 // BTN_GEAR_UP
	KeyOk                      = 0x160 // KEY_OK
	KeySelect                  = 0x161 // KEY_SELECT
	KeyGoto                    = 0x162 // KEY_GOTO
	KeyClear                   = 0x163 // KEY_CLEAR
	KeyPower2                  = 0x164 // KEY_POWER2
	KeyOption                  = 0x165 // KEY_OPTION
	KeyInfo                    = 0x166 // KEY_INFO
	KeyTime                    = 0x167 // KEY_TIME
	KeyVendor                  = 0x168 // KEY_VENDOR
	KeyArchive                 = 0x169 // KEY_ARCHIVE
	KeyProgram                 = 0x16a // KEY_PROGRAM
	KeyChannel                 = 0x16b // KEY_CHANNEL
	KeyFavorites               = 0x16c // KEY_FAVORITES
	KeyEpg                     = 0x16d // KEY_EPG
	KeyPvr                     = 0x16e // KEY_PVR
	KeyMhp                     = 0x16f // KEY_MHP
	KeyLanguage                = 0x170 // KEY_LANGUAGE
	KeyTitle                   = 0x171 // KEY_TITLE
	KeySubtitle                = 0x172 // KEY_SUBTITLE
	KeyAngle                   = 0x173 // KEY_ANGLE
	KeyFullScreen              = 0x174 // KEY_FULL_SCREEN
	KeyZoom                    = 0x174 // KEY_ZOOM
	KeyMode                    = 0x175 // KEY_MODE
	KeyKeyboard                = 0x176 // KEY_KEYBOARD
	KeyAspectRatio             = 0x177 // KEY_ASPECT_RATIO
	KeyScreen                  = 0x177 // KEY_SCREEN
	KeyPc                      = 0x178 // KEY_PC
	KeyTv                      = 0x179 // KEY_TV
	KeyTv2                     = 0x17a // KEY_TV2
	KeyVcr                     = 0x17b // KEY_VCR
	KeyVcr2                    = 0x17c // KEY_VCR2
	KeySat                     = 0x17d // KEY_SAT
	KeySat2                    = 0x17e // KEY_SAT2
	KeyCd                      = 0x17f // KEY_CD
	KeyTape                    = 0x180 // KEY_TAPE
	KeyRadio                   = 0x181 // KEY_RADIO
	KeyTuner                   = 0x182 // KEY_TUNER
	KeyPlayer                  = 0x183 // KEY_PLAYER
	KeyText                    = 0x184 // KEY_TEXT
	KeyDvd                     = 0x185 // KEY_DVD
	KeyAux                     = 0x186 // KEY_AUX
	KeyMp3                     = 0x187 // KEY_MP3
	KeyAudio                   = 0x188 // KEY_AUDIO
	KeyVideo                   = 0x189 // KEY_VIDEO
	KeyDirectory               = 0x18a // KEY_DIRECTORY
	KeyList                    = 0x18b // KEY_LIST
	KeyMemo                    = 0x18c // KEY_MEMO
	KeyCalendar                = 0x18d // KEY_CALENDAR
	KeyRed                     = 0x18e // KEY_RED
	KeyGreen                   = 0x18f // KEY_GREEN
	KeyYellow                  = 0x190 // KEY_YELLOW
	KeyBlue                    = 0x191 // KEY_BLUE
	KeyChannelup               = 0x192 // KEY_CHANNELUP
	KeyChanneldown             = 0x193 // KEY_CHANNELDOWN
	KeyFirst                   = 0x194 // KEY_FIRST
	KeyLast                    = 0x195 // KEY_LAST
	KeyAb                      = 0x196 // KEY_AB
	KeyNext                    = 0x197 // KEY_NEXT
	KeyRestart                 = 0x198 // KEY_RESTART
	KeySlow                    = 0x199 // KEY_SLOW
	KeyShuffle                 = 0x19a // KEY_SHUFFLE
	KeyBreak                   = 0x19b // KEY_BREAK
	KeyPrevious                = 0x19c // KEY_PREVIOUS
	KeyDigits                  = 0x19d // KEY_DIGITS
	KeyTeen                    = 0x19e // KEY_TEEN
	KeyTwen                    = 0x19f // KEY_TWEN
	KeyVideophone              = 0x1a0 // KEY_VIDEOPHONE
	KeyGames                   = 0x1a1 // KEY_GAMES
	KeyZoomin                  = 0x1a2 // KEY_ZOOMIN
	KeyZoomout                 = 0x1a3 // KEY_ZOOMOUT
	KeyZoomreset               = 0x1a4 // KEY_ZOOMRESET
	KeyWordprocessor           = 0x1a5 // KEY_WORDPROCESSOR
	KeyEditor                  = 0x1a6 // KEY_EDITOR
	KeySpreadsheet             = 0x1a7 // KEY_SPREADSHEET
	KeyGraphicseditor          = 0x1a8 // KEY_GRAPHICSEDITOR
	KeyPresentation            = 0x1a9 // KEY_PRESENTATION
	KeyDatabase                = 0x1aa // KEY_DATABASE
	KeyNews                    = 0x1ab // KEY_NEWS
	KeyVoicemail               = 0x1ac // KEY_VOICEMAIL
	KeyAddressbook             = 0x1ad // KEY_ADDRESSBOOK
	KeyMessenger               = 0x1ae // KEY_MESSENGER
	KeyDisplaytoggle           = 0x1af // KEY_DISPLAYTOGGLE
	KeyBrightnessToggle        = 0x1af // KEY_BRIGHTNESS_TOGGLE
	KeySpellcheck              = 0x1b0 // KEY_SPELLCHECK
	KeyLogoff                  = 0x1b1 // KEY_LOGOFF
	KeyDollar                  = 0x1b2 // KEY_DOLLAR
	KeyEuro                    = 0x1b3 // KEY_EURO
	KeyFrameback               = 0x1b4 // KEY_FRAMEBACK
	KeyFrameforward            = 0x1b5 // KEY_FRAMEFORWARD
	KeyContextMenu             = 0x1b6 // KEY_CONTEXT_MENU
	KeyMediaRepeat             = 0x1b7 // KEY_MEDIA_REPEAT
	Key10channelsup            = 0x1b8 // KEY_10CHANNELSUP
	Key10channelsdown          = 0x1b9 // KEY_10CHANNELSDOWN
	KeyImages                  = 0x1ba // KEY_IMAGES
	KeyNotificationCenter      = 0x1bc // KEY_NOTIFICATION_CENTER
	KeyPickupPhone             = 0x1bd // KEY_PICKUP_PHONE
	KeyHangupPhone             = 0x1be // KEY_HANGUP_PHONE
	KeyLinkPhone               = 0x1bf // KEY_LINK_PHONE
	KeyDelEol                  = 0x1c0 // KEY_DEL_EOL
	KeyDelEos                  = 0x1c1 // KEY_DEL_EOS
	KeyInsLine                 = 0x1c2 // KEY_INS_LINE
	KeyDelLine                 = 0x1c3 // KEY_DEL_LINE
	KeyFn                      = 0x1d0 // KEY_FN
	KeyFnEsc                   = 0x1d1 // KEY_FN_ESC
	KeyFnF1                    = 0x1d2 // KEY_FN_F1
	KeyFnF2                    = 0x1d3 // KEY_FN_F2
	KeyFnF3                    = 0x1d4 // KEY_FN_F3
	KeyFnF4                    = 0x1d5 // KEY_FN_F4
	KeyFnF5                    = 0x1d6 // KEY_FN_F5
	KeyFnF6                    = 0x1d7 // KEY_FN_F6
	KeyFnF7                    = 0x1d8 // KEY_FN_F7
	KeyFnF8                    = 0x1d9 // KEY_FN_F8
	KeyFnF9                    = 0x1da // KEY_FN_F9
	KeyFnF10                   = 0x1db // KEY_FN_F10
	KeyFnF11                   = 0x1dc // KEY_FN_F11
	KeyFnF12                   = 0x1dd // KEY_FN_F12
	KeyFn1                     = 0x1de // KEY_FN_1
	KeyFn2                     = 0x1df // KEY_FN_2
	KeyFnD                     = 0x1e0 // KEY_FN_D
	KeyFnE                     = 0x1e1 // KEY_FN_E
	KeyFnF                     = 0x1e2 // KEY_FN_F
	KeyFnS                     = 0x1e3 // KEY_FN_S
	KeyFnB                     = 0x1e4 // KEY_FN_B
	KeyFnRightShift            = 0x1e5 // KEY_FN_RIGHT_SHIFT
	KeyBrlDot1                 = 0x1f1 // KEY_BRL_DOT1
	KeyBrlDot2                 = 0x1f2 // KEY_BRL_DOT2
	KeyBrlDot3                 = 0x1f3 // KEY_BRL_DOT3
	KeyBrlDot4                 = 0x1f4 // KEY_BRL_DOT4
	KeyBrlDot5                 = 0x1f5 // KEY_BRL_DOT5
	KeyBrlDot6                 = 0x1f6 // KEY_BRL_DOT6
	KeyBrlDot7                 = 0x1f7 // KEY_BRL_DOT7
	KeyBrlDot8                 = 0x1f8 // KEY_BRL_DOT8
	KeyBrlDot9                 = 0x1f9 // KEY_BRL_DOT9
	KeyBrlDot10                = 0x1fa // KEY_BRL_DOT10
	KeyNumeric0                = 0x200 // KEY_NUMERIC_0
	KeyNumeric1                = 0x201 // KEY_NUMERIC_1
	KeyNumeric2                = 0x202 // KEY_NUMERIC_2
	KeyNumeric3                = 0x203 // KEY_NUMERIC_3
	KeyNumeric4                = 0x204 // KEY_NUMERIC_4
	KeyNumeric5                = 0x205 // KEY_NUMERIC_5
	KeyNumeric6                = 0x206 // KEY_NUMERIC_6
	KeyNumeric7                = 0x207 // KEY_NUMERIC_7
	KeyNumeric8                = 0x208 // KEY_NUMERIC_8
	KeyNumeric9                = 0x209 // KEY_NUMERIC_9
	KeyNumericStar             = 0x20a // KEY_NUMERIC_STAR
	KeyNumericPound            = 0x20b // KEY_NUMERIC_POUND
	KeyNumericA                = 0x20c // KEY_NUMERIC_A
	KeyNumericB                = 0x20d // KEY_NUMERIC_B
	KeyNumericC                = 0x20e // KEY_NUMERIC_C
	KeyNumericD                = 0x20f // KEY_NUMERIC_D
	KeyCameraFocus             = 0x210 // KEY_CAMERA_FOCUS
	KeyWpsButton               = 0x211 // KEY_WPS_BUTTON
	KeyTouchpadToggle          = 0x212 // KEY_TOUCHPAD_TOGGLE
	KeyTouchpadOn              = 0x213 // KEY_TOUCHPAD_ON
	KeyTouchpadOff             = 0x214 // KEY_TOUCHPAD_OFF
	KeyCameraZoomin            = 0x215 // KEY_CAMERA_ZOOMIN
	KeyCameraZoomout           = 0x216 // KEY_CAMERA_ZOOMOUT
	KeyCameraUp                = 0x217 // KEY_CAMERA_UP
	KeyCameraDown              = 0x218 // KEY_CAMERA_DOWN
	KeyCameraLeft              = 0x219 // KEY_CAMERA_LEFT
	KeyCameraRight             = 0x21a // KEY_CAMERA_RIGHT
	KeyAttendantOn             = 0x21b // KEY_ATTENDANT_ON
	KeyAttendantOff            = 0x21c // KEY_ATTENDANT_OFF
	KeyAttendantToggle         = 0x21d // KEY_ATTENDANT_TOGGLE
	KeyLightsToggle            = 0x21e // KEY_LIGHTS_TOGGLE
	BtnDpadUp                  = 0x220 // BTN_DPAD_UP
	BtnDpadDown                = 0x221 // BTN_DPAD_DOWN
	BtnDpadLeft                = 0x222 // BTN_DPAD_LEFT
	BtnDpadRight               = 0x223 // BTN_DPAD_RIGHT
	KeyAlsToggle               = 0x230 // KEY_ALS_TOGGLE
	KeyRotateLockToggle        = 0x231 // KEY_ROTATE_LOCK_TOGGLE
	KeyRefreshRateToggle       = 0x232 // KEY_REFRESH_RATE_TOGGLE
	KeyButtonconfig            = 0x240 // KEY_BUTTONCONFIG
	KeyTaskmanager             = 0x241 // KEY_TASKMANAGER
	KeyJournal                 = 0x242 // KEY_JOURNAL
	KeyControlpanel            = 0x243 // KEY_CONTROLPANEL
	KeyAppselect               = 0x244 // KEY_APPSELECT
	KeyScreensaver             = 0x245 // KEY_SCREENSAVER
	KeyVoicecommand            = 0x246 // KEY_VOICECOMMAND
	KeyAssistant               = 0x247 // KEY_ASSISTANT
	KeyKbdLayoutNext           = 0x248 // KEY_KBD_LAYOUT_NEXT
	KeyEmojiPicker             = 0x249 // KEY_EMOJI_PICKER
	KeyDictate                 = 0x24a // KEY_DICTATE
	KeyCameraAccessEnable      = 0x24b // KEY_CAMERA_ACCESS_ENABLE
	KeyCameraAccessDisable     = 0x24c // KEY_CAMERA_ACCESS_DISABLE
	KeyCameraAccessToggle      = 0x24d // KEY_CAMERA_ACCESS_TOGGLE
	KeyAccessibility           = 0x24e // KEY_ACCESSIBILITY
	KeyDoNotDisturb            = 0x24f // KEY_DO_NOT_DISTURB
	KeyBrightnessMin           = 0x250 // KEY_BRIGHTNESS_MIN
	KeyBrightnessMax           = 0x251 // KEY_BRIGHTNESS_MAX
	KeyKbdinputassistPrev      = 0x260 // KEY_KBDINPUTASSIST_PREV
	KeyKbdinputassistNext      = 0x261 // KEY_KBDINPUTASSIST_NEXT
	KeyKbdinputassistPrevgroup = 0x262 // KEY_KBDINPUTASSIST_PREVGROUP
	KeyKbdinputassistNextgroup = 0x263 // KEY_KBDINPUTASSIST_NEXTGROUP
	KeyKbdinputassistAccept    = 0x264 // KEY_KBDINPUTASSIST_ACCEPT
	KeyKbdinputassistCancel    = 0x265 // KEY_KBDINPUTASSIST_CANCEL
	KeyRightUp                 = 0x266 // KEY_RIGHT_UP
	KeyRightDown               = 0x267 // KEY_RIGHT_DOWN
	KeyLeftUp                  = 0x268 // KEY_LEFT_UP
	KeyLeftDown                = 0x269 // KEY_LEFT_DOWN
	KeyRootMenu                = 0x26a // KEY_ROOT_MENU
	KeyMediaTopMenu            = 0x26b // KEY_MEDIA_TOP_MENU
	KeyNumeric11               = 0x26c // KEY_NUMERIC_11
	KeyNumeric12               = 0x26d // KEY_NUMERIC_12
	KeyAudioDesc               = 0x26e // KEY_AUDIO_DESC
	Key3dMode                  = 0x26f // KEY_3D_MODE
	KeyNextFavorite            = 0x270 // KEY_NEXT_FAVORITE
	KeyStopRecord              = 0x271 // KEY_STOP_RECORD
	KeyPauseRecord             = 0x272 // KEY_PAUSE_RECORD
	KeyVod                     = 0x273 // KEY_VOD
	KeyUnmute                  = 0x274 // KEY_UNMUTE
	KeyFastreverse             = 0x275 // KEY_FASTREVERSE
	KeySlowreverse             = 0x276 // KEY_SLOWREVERSE
	KeyData                    = 0x277 // KEY_DATA
	KeyOnscreenKeyboard        = 0x278 // KEY_ONSCREEN_KEYBOARD
	KeyPrivacyScreenToggle     = 0x279 // KEY_PRIVACY_SCREEN_TOGGLE
	KeySelectiveScreenshot     = 0x27a // KEY_SELECTIVE_SCREENSHOT
	KeyNextElement             = 0x27b // KEY_NEXT_ELEMENT
	KeyPreviousElement         = 0x27c // KEY_PREVIOUS_ELEMENT
	KeyAutopilotEngageToggle   = 0x27d // KEY_AUTOPILOT_ENGAGE_TOGGLE
	KeyMarkWaypoint            = 0x27e // KEY_MARK_WAYPOINT
	KeySos                     = 0x27f // KEY_SOS
	KeyNavChart                = 0x280 // KEY_NAV_CHART
	KeyFishingChart            = 0x281 // KEY_FISHING_CHART
	KeySingleRangeRadar        = 0x282 // KEY_SINGLE_RANGE_RADAR
	KeyDualRangeRadar          = 0x283 // KEY_DUAL_RANGE_RADAR
	KeyRadarOverlay            = 0x284 // KEY_RADAR_OVERLAY
	KeyTraditionalSonar        = 0x285 // KEY_TRADITIONAL_SONAR
	KeyClearvuSonar            = 0x286 // KEY_CLEARVU_SONAR
	KeySidevuSonar             = 0x287 // KEY_SIDEVU_SONAR
	KeyNavInfo                 = 0x288 // KEY_NAV_INFO
	KeyBrightnessMenu          = 0x289 // KEY_BRIGHTNESS_MENU
	KeyMacro1                  = 0x290 // KEY_MACRO1
	KeyMacro2                  = 0x291 // KEY_MACRO2
	KeyMacro3                  = 0x292 // KEY_MACRO3
	KeyMacro4                  = 0x293 // KEY_MACRO4
	KeyMacro5                  = 0x294 // KEY_MACRO5
	KeyMacro6                  = 0x295 // KEY_MACRO6
	KeyMacro7                  = 0x296 // KEY_MACRO7
	KeyMacro8                  = 0x297 // KEY_MACRO8
	KeyMacro9                  = 0x298 // KEY_MACRO9
	KeyMacro10                 = 0x299 // KEY_MACRO10
	KeyMacro11                 = 0x29a // KEY_MACRO11
	KeyMacro12                 = 0x29b // KEY_MACRO12
	KeyMacro13                 = 0x29c // KEY_MACRO13
	KeyMacro14                 = 0x29d // KEY_MACRO14
	KeyMacro15                 = 0x29e // KEY_MACRO15
	KeyMacro16                 = 0x29f // KEY_MACRO16
	KeyMacro17                 = 0x2a0 // KEY_MACRO17
	KeyMacro18                 = 0x2a1 // KEY_MACRO18
	KeyMacro19                 = 0x2a2 // KEY_MACRO19
	KeyMacro20                 = 0x2a3 // KEY_MACRO20
	KeyMacro21                 = 0x2a4 // KEY_MACRO21
	KeyMacro22                 = 0x2a5 // KEY_MACRO22
	KeyMacro23                 = 0x2a6 // KEY_MACRO23
	KeyMacro24                 = 0x2a7 // KEY_MACRO24
	KeyMacro25                 = 0x2a8 // KEY_MACRO25
	KeyMacro26                 = 0x2a9 // KEY_MACRO26
	KeyMacro27                 = 0x2aa // KEY_MACRO27
	KeyMacro28                 = 0x2ab // KEY_MACRO28
	KeyMacro29                 = 0x2ac // KEY_MACRO29
	KeyMacro30                 = 0x2ad // KEY_MACRO30
	KeyMacroRecordStart        = 0x2b0 // KEY_MACRO_RECORD_START
	KeyMacroRecordStop         = 0x2b1 // KEY_MACRO_RECORD_STOP
	KeyMacroPresetCycle        = 0x2b2 // KEY_MACRO_PRESET_CYCLE
	KeyMacroPreset1            = 0x2b3 // KEY_MACRO_PRESET1
	KeyMacroPreset2            = 0x2b4 // KEY_MACRO_PRESET2
	KeyMacroPreset3            = 0x2b5 // KEY_MACRO_PRESET3
	KeyKbdLcdMenu1             = 0x2b8 // KEY_KBD_LCD_MENU1
	KeyKbdLcdMenu2             = 0x2b9 // KEY_KBD_LCD_MENU2
	KeyKbdLcdMenu3             = 0x2ba // KEY_KBD_LCD_MENU3
	KeyKbdLcdMenu4             = 0x2bb // KEY_KBD_LCD_MENU4
	KeyKbdLcdMenu5             = 0x2bc // KEY_KBD_LCD_MENU5
	BtnTriggerHappy            = 0x2c0 // BTN_TRIGGER_HAPPY
	BtnTriggerHappy1           = 0x2c0 // BTN_TRIGGER_HAPPY1
	BtnTriggerHappy2           = 0x2c1 // BTN_TRIGGER_HAPPY2
	BtnTriggerHappy3           = 0x2c2 // BTN_TRIGGER_HAPPY3
	BtnTriggerHappy4           = 0x2c3 // BTN_TRIGGER_HAPPY4
	BtnTriggerHappy5           = 0x2c4 // BTN_TRIGGER_HAPPY5
	BtnTriggerHappy6           = 0x2c5 // BTN_TRIGGER_HAPPY6
	BtnTriggerHappy7           = 0x2c6 // BTN_TRIGGER_HAPPY7
	BtnTriggerHappy8           = 0x2c7 // BTN_TRIGGER_HAPPY8
	BtnTriggerHappy9           = 0x2c8 // BTN_TRIGGER_HAPPY9
	BtnTriggerHappy10          = 0x2c9 // BTN_TRIGGER_HAPPY10
	BtnTriggerHappy11          = 0x2ca // BTN_TRIGGER_HAPPY11
	BtnTriggerHappy12          = 0x2cb // BTN_TRIGGER_HAPPY12
	BtnTriggerHappy13          = 0x2cc // BTN_TRIGGER_HAPPY13
	BtnTriggerHappy14          = 0x2cd // BTN_TRIGGER_HAPPY14
	BtnTriggerHappy15          = 0x2ce // BTN_TRIGGER_HAPPY15
	BtnTriggerHappy16          = 0x2cf // BTN_TRIGGER_HAPPY16
	BtnTriggerHappy17          = 0x2d0 // BTN_TRIGGER_HAPPY17
	BtnTriggerHappy18          = 0x2d1 // BTN_TRIGGER_HAPPY18
	BtnTriggerHappy19          = 0x2d2 // BTN_TRIGGER_HAPPY19
	BtnTriggerHappy20          = 0x2d3 // BTN_TRIGGER_HAPPY20
	BtnTriggerHappy21          = 0x2d4 // BTN_TRIGGER_HAPPY21
	BtnTriggerHappy22          = 0x2d5 // BTN_TRIGGER_HAPPY22
	BtnTriggerHappy23          = 0x2d6 // BTN_TRIGGER_HAPPY23
	BtnTriggerHappy24          = 0x2d7 // BTN_TRIGGER_HAPPY24
	BtnTriggerHappy25          = 0x2d8 // BTN_TRIGGER_HAPPY25
	BtnTriggerHappy26          = 0x2d9 // BTN_TRIGGER_HAPPY26
	BtnTriggerHappy27          = 0x2da // BTN_TRIGGER_HAPPY27
	BtnTriggerHappy28          = 0x2db // BTN_TRIGGER_HAPPY28
	BtnTriggerHappy29          = 0x2dc // BTN_TRIGGER_HAPPY29
	BtnTriggerHappy30          = 0x2dd // BTN_TRIGGER_HAPPY30
	BtnTriggerHappy31          = 0x2de // BTN_TRIGGER_HAPPY31
	BtnTriggerHappy32          = 0x2df // BTN_TRIGGER_HAPPY32
	BtnTriggerHappy33          = 0x2e0 // BTN_TRIGGER_HAPPY33
	BtnTriggerHappy34          = 0x2e1 // BTN_TRIGGER_HAPPY34
	BtnTriggerHappy35          = 0x2e2 // BTN_TRIGGER_HAPPY35
	BtnTriggerHappy36          = 0x2e3 // BTN_TRIGGER_HAPPY36
	BtnTriggerHappy37          = 0x2e4 // BTN_TRIGGER_HAPPY37
	BtnTriggerHappy38          = 0x2e5 // BTN_TRIGGER_HAPPY38
	BtnTriggerHappy39          = 0x2e6 // BTN_TRIGGER_HAPPY39
	BtnTriggerHappy40          = 0x2e7 // BTN_TRIGGER_HAPPY40
	KeyMinInteresting          = 0x71  // KEY_MIN_INTERESTING
	KeyMax                     = 0x2ff // KEY_MAX
	KeyCnt                     = 0x300 // KEY_CNT
	RelX                       = 0x0   // REL_X
	RelY                       = 0x1   // REL_Y
	RelZ                       = 0x2   // REL_Z
	RelRx                      = 0x3   // REL_RX
	RelRy                      = 0x4   // REL_RY
	RelRz                      = 0x5   // REL_RZ
	RelHwheel                  = 0x6   // REL_HWHEEL
	RelDial                    = 0x7   // REL_DIAL
	RelWheel                   = 0x8   // REL_WHEEL
	RelMisc                    = 0x9   // REL_MISC
	RelReserved                = 0xa   // REL_RESERVED
	RelWheelHiRes              = 0xb   // REL_WHEEL_HI_RES
	RelHwheelHiRes             = 0xc   // REL_HWHEEL_HI_RES
	RelMax                     = 0xf   // REL_MAX
	RelCnt                     = 0x10  // REL_CNT
	AbsX                       = 0x0   // ABS_X
	AbsY                       = 0x1   // ABS_Y
	AbsZ                       = 0x2   // ABS_Z
	AbsRx                      = 0x3   // ABS_RX
	AbsRy                      = 0x4   // ABS_RY
	AbsRz                      = 0x5   // ABS_RZ
	AbsThrottle                = 0x6   // ABS_THROTTLE
	AbsRudder                  = 0x7   // ABS_RUDDER
	AbsWheel                   = 0x8   // ABS_WHEEL
	AbsGas                     = 0x9   // ABS_GAS
	AbsBrake                   = 0xa   // ABS_BRAKE
	AbsHat0x                   = 0x10  // ABS_HAT0X
	AbsHat0y                   = 0x11  // ABS_HAT0Y
	AbsHat1x                   = 0x12  // ABS_HAT1X
	AbsHat1y                   = 0x13  // ABS_HAT1Y
	AbsHat2x                   = 0x14  // ABS_HAT2X
	AbsHat2y                   = 0x15  // ABS_HAT2Y
	AbsHat3x                   = 0x16  // ABS_HAT3X
	AbsHat3y                   = 0x17  // ABS_HAT3Y
	AbsPressure                = 0x18  // ABS_PRESSURE
	AbsDistance                = 0x19  // ABS_DISTANCE
	AbsTiltX                   = 0x1a  // ABS_TILT_X
	AbsTiltY                   = 0x1b  // ABS_TILT_Y
	AbsToolWidth               = 0x1c  // ABS_TOOL_WIDTH
	AbsVolume                  = 0x20  // ABS_VOLUME
	AbsProfile                 = 0x21  // ABS_PROFILE
	AbsMisc                    = 0x28  // ABS_MISC
	AbsReserved                = 0x2e  // ABS_RESERVED
	AbsMtSlot                  = 0x2f  // ABS_MT_SLOT
	AbsMtTouchMajor            = 0x30  // ABS_MT_TOUCH_MAJOR
	AbsMtTouchMinor            = 0x31  // ABS_MT_TOUCH_MINOR
	AbsMtWidthMajor            = 0x32  // ABS_MT_WIDTH_MAJOR
	AbsMtWidthMinor            = 0x33  // ABS_MT_WIDTH_MINOR
	AbsMtOrientation           = 0x34  // ABS_MT_ORIENTATION
	AbsMtPositionX             = 0x35  // ABS_MT_POSITION_X
	AbsMtPositionY             = 0x36  // ABS_MT_POSITION_Y
	AbsMtToolType              = 0x37  // ABS_MT_TOOL_TYPE
	AbsMtBlobId                = 0x38  // ABS_MT_BLOB_ID
	AbsMtTrackingId            = 0x39  // ABS_MT_TRACKING_ID
	AbsMtPressure              = 0x3a  // ABS_MT_PRESSURE
	AbsMtDistance              = 0x3b  // ABS_MT_DISTANCE
	AbsMtToolX                 = 0x3c  // ABS_MT_TOOL_X
	AbsMtToolY                 = 0x3d  // ABS_MT_TOOL_Y
	AbsMax                     = 0x3f  // ABS_MAX
	AbsCnt                     = 0x40  // ABS_CNT
	SwLid                      = 0x0   // SW_LID
	SwTabletMode               = 0x1   // SW_TABLET_MODE
	SwHeadphoneInsert          = 0x2   // SW_HEADPHONE_INSERT
	SwRfkillAll                = 0x3   // SW_RFKILL_ALL
	SwRadio                    = 0x3   // SW_RADIO
	SwMicrophoneInsert         = 0x4   // SW_MICROPHONE_INSERT
	SwDock                     = 0x5   // SW_DOCK
	SwLineoutInsert            = 0x6   // SW_LINEOUT_INSERT
	SwJackPhysicalInsert       = 0x7   // SW_JACK_PHYSICAL_INSERT
	SwVideooutInsert           = 0x8   // SW_VIDEOOUT_INSERT
	SwCameraLensCover          = 0x9   // SW_CAMERA_LENS_COVER
	SwKeypadSlide              = 0xa   // SW_KEYPAD_SLIDE
	SwFrontProximity           = 0xb   // SW_FRONT_PROXIMITY
	SwRotateLock               = 0xc   // SW_ROTATE_LOCK
	SwLineinInsert             = 0xd   // SW_LINEIN_INSERT
	SwMuteDevice               = 0xe   // SW_MUTE_DEVICE
	SwPenInserted              = 0xf   // SW_PEN_INSERTED
	SwMachineCover             = 0x10  // SW_MACHINE_COVER
	SwMax                      = 0x10  // SW_MAX
	SwCnt                      = 0x11  // SW_CNT
	MscSerial                  = 0x0   // MSC_SERIAL
	MscPulseled                = 0x1   // MSC_PULSELED
	MscGesture                 = 0x2   // MSC_GESTURE
	MscRaw                     = 0x3   // MSC_RAW
	MscScan                    = 0x4   // MSC_SCAN
	MscTimestamp               = 0x5   // MSC_TIMESTAMP
	MscMax                     = 0x7   // MSC_MAX
	MscCnt                     = 0x8   // MSC_CNT
	LedNuml                    = 0x0   // LED_NUML
	LedCapsl                   = 0x1   // LED_CAPSL
	LedScrolll                 = 0x2   // LED_SCROLLL
	LedCompose                 = 0x3   // LED_COMPOSE
	LedKana                    = 0x4   // LED_KANA
	LedSleep                   = 0x5   // LED_SLEEP
	LedSuspend                 = 0x6   // LED_SUSPEND
	LedMute                    = 0x7   // LED_MUTE
	LedMisc                    = 0x8   // LED_MISC
	LedMail                    = 0x9   // LED_MAIL
	LedCharging                = 0xa   // LED_CHARGING
	LedMax                     = 0xf   // LED_MAX
	LedCnt                     = 0x10  // LED_CNT
	RepDelay                   = 0x0   // REP_DELAY
	RepPeriod                  = 0x1   // REP_PERIOD
	RepMax                     = 0x1   // REP_MAX
	RepCnt                     = 0x2   // REP_CNT
	SndClick                   = 0x0   // SND_CLICK
	SndBell                    = 0x1   // SND_BELL
	SndTone                    = 0x2   // SND_TONE
	SndMax                     = 0x7   // SND_MAX
	SndCnt                     = 0x8   // SND_CNT
)

// codeNames — канонические имена кодов ядра по группам: группа → код → имя.
var codeNames = map[string]map[uint16]string{
	"ABS": {
		0x0:  "ABS_X",
		0x1:  "ABS_Y",
		0x2:  "ABS_Z",
		0x3:  "ABS_RX",
		0x4:  "ABS_RY",
		0x5:  "ABS_RZ",
		0x6:  "ABS_THROTTLE",
		0x7:  "ABS_RUDDER",
		0x8:  "ABS_WHEEL",
		0x9:  "ABS_GAS",
		0xa:  "ABS_BRAKE",
		0x10: "ABS_HAT0X",
		0x11: "ABS_HAT0Y",
		0x12: "ABS_HAT1X",
		0x13: "ABS_HAT1Y",
		0x14: "ABS_HAT2X",
		0x15: "ABS_HAT2Y",
		0x16: "ABS_HAT3X",
		0x17: "ABS_HAT3Y",
		0x18: "ABS_PRESSURE",
		0x19: "ABS_DISTANCE",
		0x1a: "ABS_TILT_X",
		0x1b: "ABS_TILT_Y",
		0x1c: "ABS_TOOL_WIDTH",
		0x20: "ABS_VOLUME",
		0x21: "ABS_PROFILE",
		0x28: "ABS_MISC",
		0x2e: "ABS_RESERVED",
		0x2f: "ABS_MT_SLOT",
		0x30: "ABS_MT_TOUCH_MAJOR",
		0x31: "ABS_MT_TOUCH_MINOR",
		0x32: "ABS_MT_WIDTH_MAJOR",
		0x33: "ABS_MT_WIDTH_MINOR",
		0x34: "ABS_MT_ORIENTATION",
		0x35: "ABS_MT_POSITION_X",
		0x36: "ABS_MT_POSITION_Y",
		0x37: "ABS_MT_TOOL_TYPE",
		0x38: "ABS_MT_BLOB_ID",
		0x39: "ABS_MT_TRACKING_ID",
		0x3a: "ABS_MT_PRESSURE",
		0x3b: "ABS_MT_DISTANCE",
		0x3c: "ABS_MT_TOOL_X",
		0x3d: "ABS_MT_TOOL_Y",
	},
	"EV": {
		0x0:  "EV_SYN",
		0x1:  "EV_KEY",
		0x2:  "EV_REL",
		0x3:  "EV_ABS",
		0x4:  "EV_MSC",
		0x5:  "EV_SW",
		0x11: "EV_LED",
		0x12: "EV_SND",
		0x14: "EV_REP",
		0x15: "EV_FF",
		0x16: "EV_PWR",
		0x17: "EV_FF_STATUS",
	},
	"INPUT_PROP": {
		0x0: "INPUT_PROP_POINTER",
		0x1: "INPUT_PROP_DIRECT",
		0x2: "INPUT_PROP_BUTTONPAD",
		0x3: "INPUT_PROP_SEMI_MT",
		0x4: "INPUT_PROP_TOPBUTTONPAD",
		0x5: "INPUT_PROP_POINTING_STICK",
		0x6: "INPUT_PROP_ACCELEROMETER",
	},
	"KEY": {
		0x0:   "KEY_RESERVED",
		0x1:   "KEY_ESC",
		0x2:   "KEY_1",
		0x3:   "KEY_2",
		0x4:   "KEY_3",
		0x5:   "KEY_4",
		0x6:   "KEY_5",
		0x7:   "KEY_6",
		0x8:   "KEY_7",
		0x9:   "KEY_8",
		0xa:   "KEY_9",
		0xb:   "KEY_0",
		0xc:   "KEY_MINUS",
		0xd:   "KEY_EQUAL",
		0xe:   "KEY_BACKSPACE",
		0xf:   "KEY_TAB",
		0x10:  "KEY_Q",
		0x11:  "KEY_W",
		0x12:  "KEY_E",
		0x13:  "KEY_R",
		0x14:  "KEY_T",
		0x15:  "KEY_Y",
		0x16:  "KEY_U",
		0x17:  "KEY_I",
		0x18:  "KEY_O",
		0x19:  "KEY_P",
		0x1a:  "KEY_LEFTBRACE",
		0x1b:  "KEY_RIGHTBRACE",
		0x1c:  "KEY_ENTER",
		0x1d:  "KEY_LEFTCTRL",
		0x1e:  "KEY_A",
		0x1f:  "KEY_S",
		0x20:  "KEY_D",
		0x21:  "KEY_F",
		0x22:  "KEY_G",
		0x23:  "KEY_H",
		0x24:  "KEY_J",
		0x25:  "KEY_K",
		0x26:  "KEY_L",
		0x27:  "KEY_SEMICOLON",
		0x28:  "KEY_APOSTROPHE",
		0x29:  "KEY_GRAVE",
		0x2a:  "KEY_LEFTSHIFT",
		0x2b:  "KEY_BACKSLASH",
		0x2c:  "KEY_Z",
		0x2d:  "KEY_X",
		0x2e:  "KEY_C",
		0x2f:  "KEY_V",
		0x30:  "KEY_B",
		0x31:  "KEY_N",
		0x32:  "KEY_M",
		0x33:  "KEY_COMMA",
		0x34:  "KEY_DOT",
		0x35:  "KEY_SLASH",
		0x36:  "KEY_RIGHTSHIFT",
		0x37:  "KEY_KPASTERISK",
		0x38:  "KEY_LEFTALT",
		0x39:  "KEY_SPACE",
		0x3a:  "KEY_CAPSLOCK",
		0x3b:  "KEY_F1",
		0x3c:  "KEY_F2",
		0x3d:  "KEY_F3",
		0x3e:  "KEY_F4",
		0x3f:  "KEY_F5",
		0x40:  "KEY_F6",
		0x41:  "KEY_F7",
		0x42:  "KEY_F8",
		0x43:  "KEY_F9",
		0x44:  "KEY_F10",
		0x45:  "KEY_NUMLOCK",
		0x46:  "KEY_SCROLLLOCK",
		0x47:  "KEY_KP7",
		0x48:  "KEY_KP8",
		0x49:  "KEY_KP9",
		0x4a:  "KEY_KPMINUS",
		0x4b:  "KEY_KP4",
		0x4c:  "KEY_KP5",
		0x4d:  "KEY_KP6",
		0x4e:  "KEY_KPPLUS",
		0x4f:  "KEY_KP1",
		0x50:  "KEY_KP2",
		0x51:  "KEY_KP3",
		0x52:  "KEY_KP0",
		0x53:  "KEY_KPDOT",
		0x55:  "KEY_ZENKAKUHANKAKU",
		0x56:  "KEY_102ND",
		0x57:  "KEY_F11",
		0x58:  "KEY_F12",
		0x59:  "KEY_RO",
		0x5a:  "KEY_KATAKANA",
		0x5b:  "KEY_HIRAGANA",
		0x5c:  "KEY_HENKAN",
		0x5d:  "KEY_KATAKANAHIRAGANA",
		0x5e:  "KEY_MUHENKAN",
		0x5f:  "KEY_KPJPCOMMA",
		0x60:  "KEY_KPENTER",
		0x61:  "KEY_RIGHTCTRL",
		0x62:  "KEY_KPSLASH",
		0x63:  "KEY_SYSRQ",
		0x64:  "KEY_RIGHTALT",
		0x65:  "KEY_LINEFEED",
		0x66:  "KEY_HOME",
		0x67:  "KEY_UP",
		0x68:  "KEY_PAGEUP",
		0x69:  "KEY_LEFT",
		0x6a:  "KEY_RIGHT",
		0x6b:  "KEY_END",
		0x6c:  "KEY_DOWN",
		0x6d:  "KEY_PAGEDOWN",
		0x6e:  "KEY_INSERT",
		0x6f:  "KEY_DELETE",
		0x70:  "KEY_MACRO",
		0x71:  "KEY_MUTE",
		0x72:  "KEY_VOLUMEDOWN",
		0x73:  "KEY_VOLUMEUP",
		0x74:  "KEY_POWER",
		0x75:  "KEY_KPEQUAL",
		0x76:  "KEY_KPPLUSMINUS",
		0x77:  "KEY_PAUSE",
		0x78:  "KEY_SCALE",
		0x79:  "KEY_KPCOMMA",
		0x7a:  "KEY_HANGEUL",
		0x7b:  "KEY_HANJA",
		0x7c:  "KEY_YEN",
		0x7d:  "KEY_LEFTMETA",
		0x7e:  "KEY_RIGHTMETA",
		0x7f:  "KEY_COMPOSE",
		0x80:  "KEY_STOP",
		0x81:  "KEY_AGAIN",
		0x82:  "KEY_PROPS",
		0x83:  "KEY_UNDO",
		0x84:  "KEY_FRONT",
		0x85:  "KEY_COPY",
		0x86:  "KEY_OPEN",
		0x87:  "KEY_PASTE",
		0x88:  "KEY_FIND",
		0x89:  "KEY_CUT",
		0x8a:  "KEY_HELP",
		0x8b:  "KEY_MENU",
		0x8c:  "KEY_CALC",
		0x8d:  "KEY_SETUP",
		0x8e:  "KEY_SLEEP",
		0x8f:  "KEY_WAKEUP",
		0x90:  "KEY_FILE",
		0x91:  "KEY_SENDFILE",
		0x92:  "KEY_DELETEFILE",
		0x93:  "KEY_XFER",
		0x94:  "KEY_PROG1",
		0x95:  "KEY_PROG2",
		0x96:  "KEY_WWW",
		0x97:  "KEY_MSDOS",
		0x98:  "KEY_COFFEE",
		0x99:  "KEY_ROTATE_DISPLAY",
		0x9a:  "KEY_CYCLEWINDOWS",
		0x9b:  "KEY_MAIL",
		0x9c:  "KEY_BOOKMARKS",
		0x9d:  "KEY_COMPUTER",
		0x9e:  "KEY_BACK",
		0x9f:  "KEY_FORWARD",
		0xa0:  "KEY_CLOSECD",
		0xa1:  "KEY_EJECTCD",
		0xa2:  "KEY_EJECTCLOSECD",
		0xa3:  "KEY_NEXTSONG",
		0xa4:  "KEY_PLAYPAUSE",
		0xa5:  "KEY_PREVIOUSSONG",
		0xa6:  "KEY_STOPCD",
		0xa7:  "KEY_RECORD",
		0xa8:  "KEY_REWIND",
		0xa9:  "KEY_PHONE",
		0xaa:  "KEY_ISO",
		0xab:  "KEY_CONFIG",
		0xac:  "KEY_HOMEPAGE",
		0xad:  "KEY_REFRESH",
		0xae:  "KEY_EXIT",
		0xaf:  "KEY_MOVE",
		0xb0:  "KEY_EDIT",
		0xb1:  "KEY_SCROLLUP",
		0xb2:  "KEY_SCROLLDOWN",
		0xb3:  "KEY_KPLEFTPAREN",
		0xb4:  "KEY_KPRIGHTPAREN",
		0xb5:  "KEY_NEW",
		0xb6:  "KEY_REDO",
		0xb7:  "KEY_F13",
		0xb8:  "KEY_F14",
		0xb9:  "KEY_F15",
		0xba:  "KEY_F16",
		0xbb:  "KEY_F17",
		0xbc:  "KEY_F18",
		0xbd:  "KEY_F19",
		0xbe:  "KEY_F20",
		0xbf:  "KEY_F21",
		0xc0:  "KEY_F22",
		0xc1:  "KEY_F23",
		0xc2:  "KEY_F24",
		0xc8:  "KEY_PLAYCD",
		0xc9:  "KEY_PAUSECD",
		0xca:  "KEY_PROG3",
		0xcb:  "KEY_PROG4",
		0xcc:  "KEY_ALL_APPLICATIONS",
		0xcd:  "KEY_SUSPEND",
		0xce:  "KEY_CLOSE",
		0xcf:  "KEY_PLAY",
		0xd0:  "KEY_FASTFORWARD",
		0xd1:  "KEY_BASSBOOST",
		0xd2:  "KEY_PRINT",
		0xd3:  "KEY_HP",
		0xd4:  "KEY_CAMERA",
		0xd5:  "KEY_SOUND",
		0xd6:  "KEY_QUESTION",
		0xd7:  "KEY_EMAIL",
		0xd8:  "KEY_CHAT",
		0xd9:  "KEY_SEARCH",
		0xda:  "KEY_CONNECT",
		0xdb:  "KEY_FINANCE",
		0xdc:  "KEY_SPORT",
		0xdd:  "KEY_SHOP",
		0xde:  "KEY_ALTERASE",
		0xdf:  "KEY_CANCEL",
		0xe0:  "KEY_BRIGHTNESSDOWN",
		0xe1:  "KEY_BRIGHTNESSUP",
		0xe2:  "KEY_MEDIA",
		0xe3:  "KEY_SWITCHVIDEOMODE",
		0xe4:  "KEY_KBDILLUMTOGGLE",
		0xe5:  "KEY_KBDILLUMDOWN",
		0xe6:  "KEY_KBDILLUMUP",
		0xe7:  "KEY_SEND",
		0xe8:  "KEY_REPLY",
		0xe9:  "KEY_FORWARDMAIL",
		0xea:  "KEY_SAVE",
		0xeb:  "KEY_DOCUMENTS",
		0xec:  "KEY_BATTERY",
		0xed:  "KEY_BLUETOOTH",
		0xee:  "KEY_WLAN",
		0xef:  "KEY_UWB",
		0xf0:  "KEY_UNKNOWN",
		0xf1:  "KEY_VIDEO_NEXT",
		0xf2:  "KEY_VIDEO_PREV",
		0xf3:  "KEY_BRIGHTNESS_CYCLE",
		0xf4:  "KEY_BRIGHTNESS_AUTO",
		0xf5:  "KEY_DISPLAY_OFF",
		0xf6:  "KEY_WWAN",
		0xf7:  "KEY_RFKILL",
		0xf8:  "KEY_MICMUTE",
		0x100: "BTN_0",
		0x101: "BTN_1",
		0x102: "BTN_2",
		0x103: "BTN_3",
		0x104: "BTN_4",
		0x105: "BTN_5",
		0x106: "BTN_6",
		0x107: "BTN_7",
		0x108: "BTN_8",
		0x109: "BTN_9",
		0x110: "BTN_LEFT",
		0x111: "BTN_RIGHT",
		0x112: "BTN_MIDDLE",
		0x113: "BTN_SIDE",
		0x114: "BTN_EXTRA",
		0x115: "BTN_FORWARD",
		0x116: "BTN_BACK",
		0x117: "BTN_TASK",
		0x120: "BTN_TRIGGER",
		0x121: "BTN_THUMB",
		0x122: "BTN_THUMB2",
		0x123: "BTN_TOP",
		0x124: "BTN_TOP2",
		0x125: "BTN_PINKIE",
		0x126: "BTN_BASE",
		0x127: "BTN_BASE2",
		0x128: "BTN_BASE3",
		0x129: "BTN_BASE4",
		0x12a: "BTN_BASE5",
		0x12b: "BTN_BASE6",
		0x12f: "BTN_DEAD",
		0x130: "BTN_SOUTH",
		0x131: "BTN_EAST",
		0x132: "BTN_C",
		0x133: "BTN_NORTH",
		0x134: "BTN_WEST",
		0x135: "BTN_Z",
		0x136: "BTN_TL",
		0x137: "BTN_TR",
		0x138: "BTN_TL2",
		0x139: "BTN_TR2",
		0x13a: "BTN_SELECT",
		0x13b: "BTN_START",
		0x13c: "BTN_MODE",
		0x13d: "BTN_THUMBL",
		0x13e: "BTN_THUMBR",
		0x140: "BTN_TOOL_PEN",
		0x141: "BTN_TOOL_RUBBER",
		0x142: "BTN_TOOL_BRUSH",
		0x143: "BTN_TOOL_PENCIL",
		0x144: "BTN_TOOL_AIRBRUSH",
		0x145: "BTN_TOOL_FINGER",
		0x146: "BTN_TOOL_MOUSE",
		0x147: "BTN_TOOL_LENS",
		0x148: "BTN_TOOL_QUINTTAP",
		0x149: "BTN_STYLUS3",
		0x14a: "BTN_TOUCH",
		0x14b: "BTN_STYLUS",
		0x14c: "BTN_STYLUS2",
		0x14d: "BTN_TOOL_DOUBLETAP",
		0x14e: "BTN_TOOL_TRIPLETAP",
		0x14f: "BTN_TOOL_QUADTAP",
		0x150: "BTN_GEAR_DOWN",
		0x151: "BTN_GEAR_UP",
		0x160: "KEY_OK",
		0x161: "KEY_SELECT",
		0x162: "KEY_GOTO",
		0x163: "KEY_CLEAR",
		0x164: "KEY_POWER2",
		0x165: "KEY_OPTION",
		0x166: "KEY_INFO",
		0x167: "KEY_TIME",
		0x168: "KEY_VENDOR",
		0x169: "KEY_ARCHIVE",
		0x16a: "KEY_PROGRAM",
		0x16b: "KEY_CHANNEL",
		0x16c: "KEY_FAVORITES",
		0x16d: "KEY_EPG",
		0x16e: "KEY_PVR",
		0x16f: "KEY_MHP",
		0x170: "KEY_LANGUAGE",
		0x171: "KEY_TITLE",
		0x172: "KEY_SUBTITLE",
		0x173: "KEY_ANGLE",
		0x174: "KEY_FULL_SCREEN",
		0x175: "KEY_MODE",
		0x176: "KEY_KEYBOARD",
		0x177: "KEY_ASPECT_RATIO",
		0x178: "KEY_PC",
		0x179: "KEY_TV",
		0x17a: "KEY_TV2",
		0x17b: "KEY_VCR",
		0x17c: "KEY_VCR2",
		0x17d: "KEY_SAT",
		0x17e: "KEY_SAT2",
		0x17f: "KEY_CD",
		0x180: "KEY_TAPE",
		0x181: "KEY_RADIO",
		0x182: "KEY_TUNER",
		0x183: "KEY_PLAYER",
		0x184: "KEY_TEXT",
		0x185: "KEY_DVD",
		0x186: "KEY_AUX",
		0x187: "KEY_MP3",
		0x188: "KEY_AUDIO",
		0x189: "KEY_VIDEO",
		0x18a: "KEY_DIRECTORY",
		0x18b: "KEY_LIST",
		0x18c: "KEY_MEMO",
		0x18d: "KEY_CALENDAR",
		0x18e: "KEY_RED",
		0x18f: "KEY_GREEN",
		0x190: "KEY_YELLOW",
		0x191: "KEY_BLUE",
		0x192: "KEY_CHANNELUP",
		0x193: "KEY_CHANNELDOWN",
		0x194: "KEY_FIRST",
		0x195: "KEY_LAST",
		0x196: "KEY_AB",
		0x197: "KEY_NEXT",
		0x198: "KEY_RESTART",
		0x199: "KEY_SLOW",
		0x19a: "KEY_SHUFFLE",
		0x19b: "KEY_BREAK",
		0x19c: "KEY_PREVIOUS",
		0x19d: "KEY_DIGITS",
		0x19e: "KEY_TEEN",
		0x19f: "KEY_TWEN",
		0x1a0: "KEY_VIDEOPHONE",
		0x1a1: "KEY_GAMES",
		0x1a2: "KEY_ZOOMIN",
		0x1a3: "KEY_ZOOMOUT",
		0x1a4: "KEY_ZOOMRESET",
		0x1a5: "KEY_WORDPROCESSOR",
		0x1a6: "KEY_EDITOR",
		0x1a7: "KEY_SPREADSHEET",
		0x1a8: "KEY_GRAPHICSEDITOR",
		0x1a9: "KEY_PRESENTATION",
		0x1aa: "KEY_DATABASE",
		0x1ab: "KEY_NEWS",
		0x1ac: "KEY_VOICEMAIL",
		0x1ad: "KEY_ADDRESSBOOK",
		0x1ae: "KEY_MESSENGER",
		0x1af: "KEY_DISPLAYTOGGLE",
		0x1b0: "KEY_SPELLCHECK",
		0x1b1: "KEY_LOGOFF",
		0x1b2: "KEY_DOLLAR",
		0x1b3: "KEY_EURO",
		0x1b4: "KEY_FRAMEBACK",
		0x1b5: "KEY_FRAMEFORWARD",
		0x1b6: "KEY_CONTEXT_MENU",
		0x1b7: "KEY_MEDIA_REPEAT",
		0x1b8: "KEY_10CHANNELSUP",
		0x1b9: "KEY_10CHANNELSDOWN",
		0x1ba: "KEY_IMAGES",
		0x1bc: "KEY_NOTIFICATION_CENTER",
		0x1bd: "KEY_PICKUP_PHONE",
		0x1be: "KEY_HANGUP_PHONE",
		0x1bf: "KEY_LINK_PHONE",
		0x1c0: "KEY_DEL_EOL",
		0x1c1: "KEY_DEL_EOS",
		0x1c2: "KEY_INS_LINE",
		0x1c3: "KEY_DEL_LINE",
		0x1d0: "KEY_FN",
		0x1d1: "KEY_FN_ESC",
		0x1d2: "KEY_FN_F1",
		0x1d3: "KEY_FN_F2",
		0x1d4: "KEY_FN_F3",
		0x1d5: "KEY_FN_F4",
		0x1d6: "KEY_FN_F5",
		0x1d7: "KEY_FN_F6",
		0x1d8: "KEY_FN_F7",
		0x1d9: "KEY_FN_F8",
		0x1da: "KEY_FN_F9",
		0x1db: "KEY_FN_F10",
		0x1dc: "KEY_FN_F11",
		0x1dd: "KEY_FN_F12",
		0x1de: "KEY_FN_1",
		0x1df: "KEY_FN_2",
		0x1e0: "KEY_FN_D",
		0x1e1: "KEY_FN_E",
		0x1e2: "KEY_FN_F",
		0x1e3: "KEY_FN_S",
		0x1e4: "KEY_FN_B",
		0x1e5: "KEY_FN_RIGHT_SHIFT",
		0x1f1: "KEY_BRL_DOT1",
		0x1f2: "KEY_BRL_DOT2",
		0x1f3: "KEY_BRL_DOT3",
		0x1f4: "KEY_BRL_DOT4",
		0x1f5: "KEY_BRL_DOT5",
		0x1f6: "KEY_BRL_DOT6",
		0x1f7: "KEY_BRL_DOT7",
		0x1f8: "KEY_BRL_DOT8",
		0x1f9: "KEY_BRL_DOT9",
		0x1fa: "KEY_BRL_DOT10",
		0x200: "KEY_NUMERIC_0",
		0x201: "KEY_NUMERIC_1",
		0x202: "KEY_NUMERIC_2",
		0x203: "KEY_NUMERIC_3",
		0x204: "KEY_NUMERIC_4",
		0x205: "KEY_NUMERIC_5",
		0x206: "KEY_NUMERIC_6",
		0x207: "KEY_NUMERIC_7",
		0x208: "KEY_NUMERIC_8",
		0x209: "KEY_NUMERIC_9",
		0x20a: "KEY_NUMERIC_STAR",
		0x20b: "KEY_NUMERIC_POUND",
		0x20c: "KEY_NUMERIC_A",
		0x20d: "KEY_NUMERIC_B",
		0x20e: "KEY_NUMERIC_C",
		0x20f: "KEY_NUMERIC_D",
		0x210: "KEY_CAMERA_FOCUS",
		0x211: "KEY_WPS_BUTTON",
		0x212: "KEY_TOUCHPAD_TOGGLE",
		0x213: "KEY_TOUCHPAD_ON",
		0x214: "KEY_TOUCHPAD_OFF",
		0x215: "KEY_CAMERA_ZOOMIN",
		0x216: "KEY_CAMERA_ZOOMOUT",
		0x217: "KEY_CAMERA_UP",
		0x218: "KEY_CAMERA_DOWN",
		0x219: "KEY_CAMERA_LEFT",
		0x21a: "KEY_CAMERA_RIGHT",
		0x21b: "KEY_ATTENDANT_ON",
		0x21c: "KEY_ATTENDANT_OFF",
		0x21d: "KEY_ATTENDANT_TOGGLE",
		0x21e: "KEY_LIGHTS_TOGGLE",
		0x220: "BTN_DPAD_UP",
		0x221: "BTN_DPAD_DOWN",
		0x222: "BTN_DPAD_LEFT",
		0x223: "BTN_DPAD_RIGHT",
		0x230: "KEY_ALS_TOGGLE",
		0x231: "KEY_ROTATE_LOCK_TOGGLE",
		0x232: "KEY_REFRESH_RATE_TOGGLE",
		0x240: "KEY_BUTTONCONFIG",
		0x241: "KEY_TASKMANAGER",
		0x242: "KEY_JOURNAL",
		0x243: "KEY_CONTROLPANEL",
		0x244: "KEY_APPSELECT",
		0x245: "KEY_SCREENSAVER",
		0x246: "KEY_VOICECOMMAND",
		0x247: "KEY_ASSISTANT",
		0x248: "KEY_KBD_LAYOUT_NEXT",
		0x249: "KEY_EMOJI_PICKER",
		0x24a: "KEY_DICTATE",
		0x24b: "KEY_CAMERA_ACCESS_ENABLE",
		0x24c: "KEY_CAMERA_ACCESS_DISABLE",
		0x24d: "KEY_CAMERA_ACCESS_TOGGLE",
		0x24e: "KEY_ACCESSIBILITY",
		0x24f: "KEY_DO_NOT_DISTURB",
		0x250: "KEY_BRIGHTNESS_MIN",
		0x260: "KEY_KBDINPUTASSIST_PREV",
		0x261: "KEY_KBDINPUTASSIST_NEXT",
		0x262: "KEY_KBDINPUTASSIST_PREVGROUP",
		0x263: "KEY_KBDINPUTASSIST_NEXTGROUP",
		0x264: "KEY_KBDINPUTASSIST_ACCEPT",
		0x265: "KEY_KBDINPUTASSIST_CANCEL",
		0x266: "KEY_RIGHT_UP",
		0x267: "KEY_RIGHT_DOWN",
		0x268: "KEY_LEFT_UP",
		0x269: "KEY_LEFT_DOWN",
		0x26a: "KEY_ROOT_MENU",
		0x26b: "KEY_MEDIA_TOP_MENU",
		0x26c: "KEY_NUMERIC_11",
		0x26d: "KEY_NUMERIC_12",
		0x26e: "KEY_AUDIO_DESC",
		0x26f: "KEY_3D_MODE",
		0x270: "KEY_NEXT_FAVORITE",
		0x271: "KEY_STOP_RECORD",
		0x272: "KEY_PAUSE_RECORD",
		0x273: "KEY_VOD",
		0x274: "KEY_UNMUTE",
		0x275: "KEY_FASTREVERSE",
		0x276: "KEY_SLOWREVERSE",
		0x277: "KEY_DATA",
		0x278: "KEY_ONSCREEN_KEYBOARD",
		0x279: "KEY_PRIVACY_SCREEN_TOGGLE",
		0x27a: "KEY_SELECTIVE_SCREENSHOT",
		0x27b: "KEY_NEXT_ELEMENT",
		0x27c: "KEY_PREVIOUS_ELEMENT",
		0x27d: "KEY_AUTOPILOT_ENGAGE_TOGGLE",
		0x27e: "KEY_MARK_WAYPOINT",
		0x27f: "KEY_SOS",
		0x280: "KEY_NAV_CHART",
		0x281: "KEY_FISHING_CHART",
		0x282: "KEY_SINGLE_RANGE_RADAR",
		0x283: "KEY_DUAL_RANGE_RADAR",
		0x284: "KEY_RADAR_OVERLAY",
		0x285: "KEY_TRADITIONAL_SONAR",
		0x286: "KEY_CLEARVU_SONAR",
		0x287: "KEY_SIDEVU_SONAR",
		0x288: "KEY_NAV_INFO",
		0x289: "KEY_BRIGHTNESS_MENU",
		0x290: "KEY_MACRO1",
		0x291: "KEY_MACRO2",
		0x292: "KEY_MACRO3",
		0x293: "KEY_MACRO4",
		0x294: "KEY_MACRO5",
		0x295: "KEY_MACRO6",
		0x296: "KEY_MACRO7",
		0x297: "KEY_MACRO8",
		0x298: "KEY_MACRO9",
		0x299: "KEY_MACRO10",
		0x29a: "KEY_MACRO11",
		0x29b: "KEY_MACRO12",
		0x29c: "KEY_MACRO13",
		0x29d: "KEY_MACRO14",
		0x29e: "KEY_MACRO15",
		0x29f: "KEY_MACRO16",
		0x2a0: "KEY_MACRO17",
		0x2a1: "KEY_MACRO18",
		0x2a2: "KEY_MACRO19",
		0x2a3: "KEY_MACRO20",
		0x2a4: "KEY_MACRO21",
		0x2a5: "KEY_MACRO22",
		0x2a6: "KEY_MACRO23",
		0x2a7: "KEY_MACRO24",
		0x2a8: "KEY_MACRO25",
		0x2a9: "KEY_MACRO26",
		0x2aa: "KEY_MACRO27",
		0x2ab: "KEY_MACRO28",
		0x2ac: "KEY_MACRO29",
		0x2ad: "KEY_MACRO30",
		0x2b0: "KEY_MACRO_RECORD_START",
		0x2b1: "KEY_MACRO_RECORD_STOP",
		0x2b2: "KEY_MACRO_PRESET_CYCLE",
		0x2b3: "KEY_MACRO_PRESET1",
		0x2b4: "KEY_MACRO_PRESET2",
		0x2b5: "KEY_MACRO_PRESET3",
		0x2b8: "KEY_KBD_LCD_MENU1",
		0x2b9: "KEY_KBD_LCD_MENU2",
		0x2ba: "KEY_KBD_LCD_MENU3",
		0x2bb: "KEY_KBD_LCD_MENU4",
		0x2bc: "KEY_KBD_LCD_MENU5",
		0x2c0: "BTN_TRIGGER_HAPPY1",
		0x2c1: "BTN_TRIGGER_HAPPY2",
		0x2c2: "BTN_TRIGGER_HAPPY3",
		0x2c3: "BTN_TRIGGER_HAPPY4",
		0x2c4: "BTN_TRIGGER_HAPPY5",
		0x2c5: "BTN_TRIGGER_HAPPY6",
		0x2c6: "BTN_TRIGGER_HAPPY7",
		0x2c7: "BTN_TRIGGER_HAPPY8",
		0x2c8: "BTN_TRIGGER_HAPPY9",
		0x2c9: "BTN_TRIGGER_HAPPY10",
		0x2ca: "BTN_TRIGGER_HAPPY11",
		0x2cb: "BTN_TRIGGER_HAPPY12",
		0x2cc: "BTN_TRIGGER_HAPPY13",
		0x2cd: "BTN_TRIGGER_HAPPY14",
		0x2ce: "BTN_TRIGGER_HAPPY15",
		0x2cf: "BTN_TRIGGER_HAPPY16",
		0x2d0: "BTN_TRIGGER_HAPPY17",
		0x2d1: "BTN_TRIGGER_HAPPY18",
		0x2d2: "BTN_TRIGGER_HAPPY19",
		0x2d3: "BTN_TRIGGER_HAPPY20",
		0x2d4: "BTN_TRIGGER_HAPPY21",
		0x2d5: "BTN_TRIGGER_HAPPY22",
		0x2d6: "BTN_TRIGGER_HAPPY23",
		0x2d7: "BTN_TRIGGER_HAPPY24",
		0x2d8: "BTN_TRIGGER_HAPPY25",
		0x2d9: "BTN_TRIGGER_HAPPY26",
		0x2da: "BTN_TRIGGER_HAPPY27",
		0x2db: "BTN_TRIGGER_HAPPY28",
		0x2dc: "BTN_TRIGGER_HAPPY29",
		0x2dd: "BTN_TRIGGER_HAPPY30",
		0x2de: "BTN_TRIGGER_HAPPY31",
		0x2df: "BTN_TRIGGER_HAPPY32",
		0x2e0: "BTN_TRIGGER_HAPPY33",
		0x2e1: "BTN_TRIGGER_HAPPY34",
		0x2e2: "BTN_TRIGGER_HAPPY35",
		0x2e3: "BTN_TRIGGER_HAPPY36",
		0x2e4: "BTN_TRIGGER_HAPPY37",
		0x2e5: "BTN_TRIGGER_HAPPY38",
		0x2e6: "BTN_TRIGGER_HAPPY39",
		0x2e7: "BTN_TRIGGER_HAPPY40",
	},
	"LED": {
		0x0: "LED_NUML",
		0x1: "LED_CAPSL",
		0x2: "LED_SCROLLL",
		0x3: "LED_COMPOSE",
		0x4: "LED_KANA",
		0x5: "LED_SLEEP",
		0x6: "LED_SUSPEND",
		0x7: "LED_MUTE",
		0x8: "LED_MISC",
		0x9: "LED_MAIL",
		0xa: "LED_CHARGING",
	},
	"MSC": {
		0x0: "MSC_SERIAL",
		0x1: "MSC_PULSELED",
		0x2: "MSC_GESTURE",
		0x3: "MSC_RAW",
		0x4: "MSC_SCAN",
		0x5: "MSC_TIMESTAMP",
	},
	"REL": {
		0x0: "REL_X",
		0x1: "REL_Y",
		0x2: "REL_Z",
		0x3: "REL_RX",
		0x4: "REL_RY",
		0x5: "REL_RZ",
		0x6: "REL_HWHEEL",
		0x7: "REL_DIAL",
		0x8: "REL_WHEEL",
		0x9: "REL_MISC",
		0xa: "REL_RESERVED",
		0xb: "REL_WHEEL_HI_RES",
		0xc: "REL_HWHEEL_HI_RES",
	},
	"REP": {
		0x0: "REP_DELAY",
		0x1: "REP_PERIOD",
	},
	"SND": {
		0x0: "SND_CLICK",
		0x1: "SND_BELL",
		0x2: "SND_TONE",
	},
	"SW": {
		0x0:  "SW_LID",
		0x1:  "SW_TABLET_MODE",
		0x2:  "SW_HEADPHONE_INSERT",
		0x3:  "SW_RFKILL_ALL",
		0x4:  "SW_MICROPHONE_INSERT",
		0x5:  "SW_DOCK",
		0x6:  "SW_LINEOUT_INSERT",
		0x7:  "SW_JACK_PHYSICAL_INSERT",
		0x8:  "SW_VIDEOOUT_INSERT",
		0x9:  "SW_CAMERA_LENS_COVER",
		0xa:  "SW_KEYPAD_SLIDE",
		0xb:  "SW_FRONT_PROXIMITY",
		0xc:  "SW_ROTATE_LOCK",
		0xd:  "SW_LINEIN_INSERT",
		0xe:  "SW_MUTE_DEVICE",
		0xf:  "SW_PEN_INSERTED",
		0x10: "SW_MACHINE_COVER",
	},
	"SYN": {
		0x0: "SYN_REPORT",
		0x1: "SYN_CONFIG",
		0x2: "SYN_MT_REPORT",
		0x3: "SYN_DROPPED",
	},
}
